In [3]:
import csv
filename = 'transactions.csv'
import pandas as pd
def read_csv_2(filename):
    x =  pd.read_csv(filename).to_dict('records')
    return x


read_csv_2(filename)

[{'title': 'Transaction1 on Food',
  'amount': 157.26,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Food'},
 {'title': 'Transaction2 on Entertainment',
  'amount': 185.03,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction3 on Fitness',
  'amount': 130.97,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction4 on Fitness',
  'amount': 75.79,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction5 on Entertainment',
  'amount': 19.74,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction6 on Fitness',
  'amount': 107.42,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction7 on Shopping',
  'amount': 53.99,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction8 on Transportation',
  'amount': 139.87,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction9 on Food',
  'amount': 90.93,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Food'},
 {'title': 'Transaction10 on Food',
  'amount': 15.43,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Food'},
 {'title': 'Transaction11 on Shopping',
  'amount': 121.89,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction12 on Food',
  'amount': 57.2,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Food'},
 {'title': 'Transaction13 on Food',
  'amount': 35.4,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Food'},
 {'title': 'Transaction14 on Shopping',
  'amount': 106.06,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction15 on Fitness',
  'amount': 146.54,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction16 on Food',
  'amount': 159.17,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Food'},
 {'title': 'Transaction17 on Shopping',
  'amount': 191.79,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction18 on Transportation',
  'amount': 183.26,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction19 on Entertainment',
  'amount': 128.06,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction20 on Transportation',
  'amount': 65.17,
  'date': 'Thu, Feb 01, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction1 on Transportation',
  'amount': 102.32,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction2 on Food',
  'amount': 182.0,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Food'},
 {'title': 'Transaction3 on Entertainment',
  'amount': 121.4,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction4 on Entertainment',
  'amount': 103.63,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction5 on Food',
  'amount': 102.73,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Food'},
 {'title': 'Transaction6 on Shopping',
  'amount': 118.79,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction7 on Shopping',
  'amount': 128.22,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction8 on Food',
  'amount': 82.62,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Food'},
 {'title': 'Transaction9 on Entertainment',
  'amount': 114.21,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction10 on Shopping',
  'amount': 169.46,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction11 on Shopping',
  'amount': 87.74,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction12 on Transportation',
  'amount': 199.42,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction13 on Food',
  'amount': 38.87,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Food'},
 {'title': 'Transaction14 on Entertainment',
  'amount': 5.1,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction15 on Entertainment',
  'amount': 108.91,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction16 on Fitness',
  'amount': 143.35,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction17 on Shopping',
  'amount': 134.05,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction18 on Entertainment',
  'amount': 199.42,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction19 on Food',
  'amount': 163.56,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Food'},
 {'title': 'Transaction20 on Transportation',
  'amount': 74.13,
  'date': 'Fri, Feb 02, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction1 on Food',
  'amount': 130.09,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Food'},
 {'title': 'Transaction2 on Entertainment',
  'amount': 155.88,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction3 on Food',
  'amount': 153.6,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Food'},
 {'title': 'Transaction4 on Food',
  'amount': 74.58,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Food'},
 {'title': 'Transaction5 on Shopping',
  'amount': 81.13,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction6 on Shopping',
  'amount': 119.19,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction7 on Entertainment',
  'amount': 150.16,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction8 on Transportation',
  'amount': 112.22,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction9 on Fitness',
  'amount': 16.26,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction10 on Entertainment',
  'amount': 167.25,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction11 on Transportation',
  'amount': 156.12,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction12 on Fitness',
  'amount': 98.75,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction13 on Fitness',
  'amount': 102.93,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction14 on Fitness',
  'amount': 67.09,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction15 on Fitness',
  'amount': 81.41,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction16 on Fitness',
  'amount': 30.73,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction17 on Fitness',
  'amount': 14.81,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction18 on Transportation',
  'amount': 14.94,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction19 on Food',
  'amount': 71.17,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Food'},
 {'title': 'Transaction20 on Fitness',
  'amount': 17.28,
  'date': 'Sat, Feb 03, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction1 on Fitness',
  'amount': 17.89,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction2 on Entertainment',
  'amount': 117.22,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction3 on Fitness',
  'amount': 63.09,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction4 on Entertainment',
  'amount': 167.83,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction5 on Entertainment',
  'amount': 141.69,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction6 on Transportation',
  'amount': 190.76,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction7 on Shopping',
  'amount': 172.12,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction8 on Food',
  'amount': 43.93,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Food'},
 {'title': 'Transaction9 on Food',
  'amount': 162.32,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Food'},
 {'title': 'Transaction10 on Shopping',
  'amount': 163.56,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction11 on Fitness',
  'amount': 129.8,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction12 on Shopping',
  'amount': 112.68,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction13 on Shopping',
  'amount': 139.4,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction14 on Entertainment',
  'amount': 143.18,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction15 on Shopping',
  'amount': 118.13,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction16 on Fitness',
  'amount': 5.56,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction17 on Entertainment',
  'amount': 15.9,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction18 on Entertainment',
  'amount': 115.24,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction19 on Fitness',
  'amount': 118.5,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction20 on Fitness',
  'amount': 107.0,
  'date': 'Sun, Feb 04, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction1 on Fitness',
  'amount': 169.72,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction2 on Food',
  'amount': 8.67,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Food'},
 {'title': 'Transaction3 on Fitness',
  'amount': 131.56,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction4 on Fitness',
  'amount': 48.23,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction5 on Shopping',
  'amount': 73.41,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction6 on Entertainment',
  'amount': 112.95,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction7 on Shopping',
  'amount': 66.69,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction8 on Entertainment',
  'amount': 102.79,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction9 on Fitness',
  'amount': 13.95,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction10 on Transportation',
  'amount': 140.27,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction11 on Transportation',
  'amount': 134.81,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction12 on Transportation',
  'amount': 48.22,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction13 on Shopping',
  'amount': 91.09,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction14 on Shopping',
  'amount': 31.12,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction15 on Transportation',
  'amount': 85.03,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction16 on Shopping',
  'amount': 74.08,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction17 on Fitness',
  'amount': 43.94,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction18 on Transportation',
  'amount': 171.07,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction19 on Fitness',
  'amount': 24.14,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction20 on Entertainment',
  'amount': 135.51,
  'date': 'Mon, Feb 05, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction1 on Transportation',
  'amount': 66.42,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction2 on Fitness',
  'amount': 196.65,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction3 on Transportation',
  'amount': 110.22,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction4 on Transportation',
  'amount': 27.77,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction5 on Transportation',
  'amount': 126.4,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction6 on Fitness',
  'amount': 187.02,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction7 on Fitness',
  'amount': 129.81,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction8 on Transportation',
  'amount': 128.06,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction9 on Entertainment',
  'amount': 30.57,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction10 on Transportation',
  'amount': 119.11,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction11 on Transportation',
  'amount': 7.63,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction12 on Transportation',
  'amount': 6.03,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction13 on Entertainment',
  'amount': 99.26,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction14 on Fitness',
  'amount': 31.32,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction15 on Transportation',
  'amount': 105.81,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction16 on Food',
  'amount': 51.66,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Food'},
 {'title': 'Transaction17 on Entertainment',
  'amount': 8.58,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction18 on Shopping',
  'amount': 40.36,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction19 on Food',
  'amount': 105.41,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Food'},
 {'title': 'Transaction20 on Transportation',
  'amount': 177.61,
  'date': 'Tue, Feb 06, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction1 on Fitness',
  'amount': 181.52,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction2 on Fitness',
  'amount': 196.45,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction3 on Shopping',
  'amount': 44.25,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction4 on Transportation',
  'amount': 160.05,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction5 on Entertainment',
  'amount': 105.89,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction6 on Food',
  'amount': 126.9,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Food'},
 {'title': 'Transaction7 on Entertainment',
  'amount': 144.95,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction8 on Entertainment',
  'amount': 49.79,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction9 on Transportation',
  'amount': 171.9,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction10 on Food',
  'amount': 178.41,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Food'},
 {'title': 'Transaction11 on Transportation',
  'amount': 8.01,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction12 on Food',
  'amount': 85.26,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Food'},
 {'title': 'Transaction13 on Transportation',
  'amount': 154.88,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction14 on Fitness',
  'amount': 57.18,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction15 on Fitness',
  'amount': 150.25,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction16 on Transportation',
  'amount': 73.96,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction17 on Shopping',
  'amount': 40.19,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction18 on Food',
  'amount': 75.1,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Food'},
 {'title': 'Transaction19 on Shopping',
  'amount': 45.15,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction20 on Food',
  'amount': 64.82,
  'date': 'Wed, Feb 07, 2024',
  'category': 'Food'},
 {'title': 'Transaction1 on Food',
  'amount': 189.31,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Food'},
 {'title': 'Transaction2 on Transportation',
  'amount': 8.56,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction3 on Transportation',
  'amount': 27.36,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction4 on Entertainment',
  'amount': 141.57,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction5 on Food',
  'amount': 114.22,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Food'},
 {'title': 'Transaction6 on Fitness',
  'amount': 130.84,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction7 on Transportation',
  'amount': 125.74,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction8 on Entertainment',
  'amount': 26.92,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction9 on Transportation',
  'amount': 180.37,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction10 on Fitness',
  'amount': 28.69,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction11 on Transportation',
  'amount': 197.78,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction12 on Food',
  'amount': 158.13,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Food'},
 {'title': 'Transaction13 on Fitness',
  'amount': 164.41,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction14 on Food',
  'amount': 29.87,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Food'},
 {'title': 'Transaction15 on Food',
  'amount': 49.51,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Food'},
 {'title': 'Transaction16 on Food',
  'amount': 113.85,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Food'},
 {'title': 'Transaction17 on Shopping',
  'amount': 24.02,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction18 on Transportation',
  'amount': 195.38,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Transportation'},
 {'title': 'Transaction19 on Entertainment',
  'amount': 54.31,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction20 on Food',
  'amount': 146.59,
  'date': 'Thu, Feb 08, 2024',
  'category': 'Food'},
 {'title': 'Transaction1 on Food',
  'amount': 131.05,
  'date': 'Fri, Feb 09, 2024',
  'category': 'Food'},
 {'title': 'Transaction2 on Entertainment',
  'amount': 51.57,
  'date': 'Fri, Feb 09, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction3 on Shopping',
  'amount': 196.73,
  'date': 'Fri, Feb 09, 2024',
  'category': 'Shopping'},
 {'title': 'Transaction4 on Entertainment',
  'amount': 33.26,
  'date': 'Fri, Feb 09, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction5 on Fitness',
  'amount': 88.77,
  'date': 'Fri, Feb 09, 2024',
  'category': 'Fitness'},
 {'title': 'Transaction6 on Entertainment',
  'amount': 77.57,
  'date': 'Fri, Feb 09, 2024',
  'category': 'Entertainment'},
 {'title': 'Transaction7 on Food',
  'amount': 52.22,
  'date': 'Fri, Feb 09, 2024',
  'category': 'Food'},
 {'title': 'Transaction8 on Food',